{% set version = '1.0-8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bradleyterry2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BradleyTerry2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BradleyTerry2/BradleyTerry2_{{ version }}.tar.gz
  sha256: 1f95e885cd68d72a06c1990e6dd6a5f9ae5e26a1cf9b5af63fbdcce27efb8625

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: prefmod
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-brglm
    - r-gtools
    - r-lme4 >=1.0
    - r-qvcalc

  run:
    - r-base
    - r-brglm
    - r-gtools
    - r-lme4 >=1.0
    - r-qvcalc

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('BradleyTerry2')"           # [not win]
    - "\"%R%\" -e \"library('BradleyTerry2')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hturner/BradleyTerry2
  license: GPL (>= 2)
  summary: Specify and fit the Bradley-Terry model, including structured versions in which the
    parameters are related to explanatory variables through a linear predictor and versions
    with contest-specific effects, such as a home advantage.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: BradleyTerry2
# Version: 1.0-8
# Title: Bradley-Terry Models
# Authors@R: c(person("Heather", "Turner", role = c("aut", "cre"), email = "ht@heatherturner.net"), person("David", "Firth", role = "aut"))
# URL: https://github.com/hturner/BradleyTerry2
# BugReports: https://github.com/hturner/BradleyTerry2/issues
# Description: Specify and fit the Bradley-Terry model, including structured versions in which the parameters are related to explanatory variables through a linear predictor and versions with contest-specific effects, such as a home advantage.
# Depends: R (>= 2.10)
# Imports: brglm, gtools, lme4 (>= 1.0), qvcalc, stats
# Suggests: prefmod
# Enhances: gnm
# License: GPL (>= 2)
# LazyData: yes
# Encoding: UTF-8
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-09-20 08:33:05 UTC; hturner
# Author: Heather Turner [aut, cre], David Firth [aut]
# Maintainer: Heather Turner <ht@heatherturner.net>
# Repository: CRAN
# Date/Publication: 2017-09-20 09:26:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
