travis:
  secure:
    BINSTAR_TOKEN: og6ts6JO2LMHfWFvnYstCq51TU6yZTPeWAIQ+ppTFHXHogObUhlKKANPBCOqhtmVvdttKcPLBcHK5WUEipJTjxWkUmvzxkxW9Gd38vqfffMr5Txm7Ft0W2gW2jTHptScVjvuMvNgRl51sKVSE3FD6CLxSTb8uerXJC57ERECualzGrLoxD+t8LsR03jXiBS5jQ2cX2LXOjQs9xdVVSRIP0AjyG5a3ZcL5mz7IUAsdZWeX8NZixQs3G9h4QjpWmcAkVP/SZ4/hQc6HV2FBXqACtv5ra5wmAdVDY95XwgX0hIJFTNUsfCiFvwKR1rfDcPXSXC369PAxU1imOhe+AxsiqHQqwPIYyqXuaWc85Hqih0Umd1cP4eEXHXq8d6HMi7MX3hsxTP68uACruY2thFcCEvGKyzeybpBjHKHL+hg8TmxyF4ikCz1RXcbXPxdvA0FJN+4UGr9LgpWaPwu2yPBYiXe19B3uIltMO7W2v5cT8I2LmYD+5PH8ccXE8KYyQnCg/550VzSJXJQ3d/oVAwvaNHFTz104vkvHX/+rA/1fOzyMk48dvDwI3jKf2v8SL6REslRVTfSaCBBxjTwXo3M0Cd5IPul6AA1P9doJ0k3RqYXbObaMfKQQss4Ei7nRDXc9TJxzYya/PWRihCtTXiCjnTupmRnXZ7GfuVJN8s56Zs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
