travis:
  secure:
    BINSTAR_TOKEN: vLMNRTC+b/bMhUUPBasUiOHLUUdWEelPV5z8d78oCJlJx728nXxJzMbeNKc4bVglG1Q67i7sdjjRWvQCHTCOe8dpIFMmHRgQY+kOCMe9mBemyOhmHUtDd+1++vom+pN0D3PWcxtpjOpmweo53NWE43+IJDdtzJ4ae1P1uQl4NIAVJk4u8T30mrK17TZhOjKWnH05/VdT3Rh+ePydbyV3JFAVT9UeLYi01KSBNzeYWWABgJ6+t8mGjOliZxqmV95H/Ktoti7dzAn4/IqIIGmpg2aYoCtScs+bFJSW30i1G4ou6+p6m4XyHzFdJdhaVV0l1IgMqAWuIBJw342A5Y/b1Or0/kxYp91CEqK7ly+TnhxezrzHXXmw+ffbDy95z97fWA2lnFpQ+0mX/l1YUFqSN66EjdNhfg/mXhKQ8wGUorbazKra07+C5SHbnV4yfJ38uinCuxlems4+w1bXGEM6nnxQU6QFVdArhe/W89WkVrb7GrtmDrVKDE0LE7bqesV/zwcIjPjuVVVi/Etxiap1syxOJw28znHLNNh9LNcHaESoGL1Y4lBOCo+jtSDyNhZ6DbjjJ+PvHfrOiGS8dwok4cfG1aqRhAtALFSuuQfp/4p47eSQVKY1PT5ftFweM3T+YOj4l8AD8c4qEB/5YAKofTFBOPi2UYFJs6lRijhIxK4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
